### ISSUE TITLE
Match instantiated object comment in remove-hooks.php more closely to file name

### ISSUE THREAD

**Issue by salcode** [bradyvercher/wp-hook-examples#1]
This is a great resource - thank you.

Most of the comments in `remove-hooks.php` match the file names in the folder `examples/` exactly, which is very helpful when reviewing.

e.g.
- Singleton => singleton.php  
- Static class => static-class.php

however, the mapping for Instantiated object is
Instantiated object => object.php

This is clear enough when reviewed closely but renaming the file `instantiated-object.php`, would remove any doubt about the mapping even on the first pass through the file.

**Comment by bradyvercher** [comment]
Glad to hear you found it helpful!

Technically, any object created using the `new` keyword is "instantiated," so even singletons and objects that aren't assigned to a variable are still instantiated. If anything, the comment could probably be adjusted if additional clarity is needed.

**Comment by salcode** [comment]
How about about adding a second comment to each section in `remove-hooks.php` with the path to the relevant file.

See #7
